version: "3"
services:
  node-app:
    # build:
    #   context: .
    #   args:
    #     NODE_ENV: production
    environment:
      - NODE_ENV=production
      - MONGO_USER=subham
      - MONGO_PASS=mypassword
      # - MONGO_USER=${MONGO_USER}
      # - MONGO_PASS=${MONGO_PASS}
    command: node app.js
  mongo:
    environment:
      # MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      # MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_INITDB_ROOT_USERNAME: subham
      MONGO_INITDB_ROOT_PASSWORD: mypassword
