version: "3"
services:
  node-app:
    # build:
    #   context: .
    #   args:
    #     NODE_ENV: development
    volumes:
      - ./:/app
    environment:
      - NODE_ENV=development
      - MONGO_USER=subham
      - MONGO_PASS=mypassword
    command: npm run dev
  mongo:
    environment:
      MONGO_INITDB_ROOT_USERNAME: subham
      MONGO_INITDB_ROOT_PASSWORD: mypassword
