version: "3"
services:
  node-app:
    image: node-app
    build: .
    ports:
      - "5000:${PORT}"
    environment:
      - PORT=${PORT}
    depends_on:
      - mongo
  mongo:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    volumes:
      - mongo-db:/data/db
volumes:
  mongo-db:
