on:
  push:
    branches: ["development"]
  pull_request:
    branches: ["development"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build docker image
        with:
          PORT: ${{ secrets.PORT }}
          MONGO_USER: ${{ secrets.MONGO_USER }}
          MONGO_PASS: ${{ secrets.MONGO_PASS }}
          MONGO_INITDB_ROOT_USERNAME: ${{ secrets.MONGO_INITDB_ROOT_USERNAME }}
          MONGO_INITDB_ROOT_PASSWORD: ${{ secrets.MONGO_INITDB_ROOT_PASSWORD }}
        run: |
          docker-compose -f docker-compose.yml -f docker-compose.dev.yml down -v
          docker-compose -f docker-compose.yml -f docker-compose.dev.yml up -d --build
          docker image prune
